#!/usr/bin/env python3
"""Convert CPC tile graphics + masks to QL Mode 8 assembly include.

Source: data/ABADIA3.BIN
  - Tile data: offset $0300 (copied to $6D00 at runtime), 8KB (256 tiles)

Each CPC tile: 4 bytes x 8 rows = 32 bytes (16 pixels wide)
Each QL tile:  4 words x 8 rows = 64 bytes (16 pixels wide)

All 256 tiles are converted.  Transparency masks are computed from
pixel data using two different transparent inks (matching CPC mask
tables generated at $3AD1, verified by Z80 trace):
  Tiles 0-127:   ink 1 is transparent (CPC mask table 1 at $9D00/$9E00)
  Tiles 128-255: ink 2 is transparent (CPC mask table 2 at $9F00/$A000)
"""

import argparse
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cpc_utils

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
DATA_DIR = os.path.join(PROJECT_DIR, "data")
SRC_DIR = os.path.join(PROJECT_DIR, "src")

TILE_DATA_OFFSET = 0x0300    # In ABADIA3.BIN
TILE_DATA_SIZE = 0x2000      # 8KB = 256 tiles x 32 bytes

CPC_TILE_BYTES = 32          # 4 bytes x 8 rows
CPC_TILE_WIDTH_BYTES = 4     # bytes per row
CPC_TILE_ROWS = 8
NUM_TILES = 256              # always convert all 256 tiles


def count_tiles(tile_data):
    """Count non-empty tiles in the data block."""
    max_tiles = len(tile_data) // CPC_TILE_BYTES
    count = 0
    for i in range(max_tiles):
        tile = tile_data[i * CPC_TILE_BYTES:(i + 1) * CPC_TILE_BYTES]
        if any(b != 0 for b in tile):
            count = i + 1
    return count


def convert_tile(tile_bytes, palette_map):
    """Convert one CPC tile (32 bytes) to QL words (32 words = 64 bytes).

    Each row: 4 CPC bytes -> 16 pixels -> 4 QL words
    Returns list of 32 QL words (8 rows x 4 words).
    """
    ql_words = []
    for row in range(CPC_TILE_ROWS):
        row_offset = row * CPC_TILE_WIDTH_BYTES
        for bx in range(CPC_TILE_WIDTH_BYTES):
            byte = tile_bytes[row_offset + bx]
            p0, p1, p2, p3 = cpc_utils.decode_mode1_byte(byte)
            word = cpc_utils.pixels_to_ql_word(p0, p1, p2, p3, palette_map)
            ql_words.append(word)
    return ql_words


def compute_per_tile_masks_from_pixels(tile_count, ql_tiles, transparent_colours):
    """Compute per-tile masks by checking pixels against transparent colour.

    For each QL word in the tile data, check each pixel position:
    - If pixel matches transparent_colour at that position -> mask bits = 1 (transparent)
    - Otherwise -> mask bits = 0 (opaque)

    transparent_colours: list of QL colour words, one per tile.
    CPC uses two different transparent inks (verified by Z80 trace):
      Tiles 0-127:   ink 1 is transparent (mask table 1 at $9D00/$9E00)
      Tiles 128-255: ink 2 is transparent (mask table 2 at $9F00/$A000)

    Returns: list of tile_count lists, each containing 32 QL mask words
    (4 words x 8 rows, aligned with tile graphics).
    """
    pixel_masks = [0xC0C0, 0x3030, 0x0C0C, 0x0303]
    all_masks = []
    for t in range(tile_count):
        transparent_colour = transparent_colours[t]
        tile_masks = []
        for word in ql_tiles[t]:
            mask_word = 0
            for px_mask in pixel_masks:
                if (word & px_mask) == (transparent_colour & px_mask):
                    mask_word |= px_mask  # this pixel is transparent
            tile_masks.append(mask_word)
        all_masks.append(tile_masks)
    return all_masks


def generate_assembly(tile_count, ql_tiles, tile_masks):
    """Generate assembly source with tile and single mask table."""
    lines = []
    lines.append("; ============================================================")
    lines.append("; tile_data.s - Tile graphics + per-tile masks for QL Mode 8")
    lines.append("; Generated by convert_tiles.py - DO NOT EDIT")
    lines.append(f"; {tile_count} tiles, {CPC_TILE_ROWS} rows x 4 words each")
    lines.append("; Masks: tiles 0-127 ink 2 transparent, tiles 128-255 ink 1 transparent")
    lines.append("; ============================================================")
    lines.append("")

    # Tile data
    lines.append("; Tile graphics: 4 words per row, 8 rows per tile")
    lines.append(f"; {tile_count} tiles x 64 bytes = {tile_count * 64} bytes")
    lines.append("tile_data:")
    for t in range(tile_count):
        lines.append(f"; Tile {t}")
        words = ql_tiles[t]
        for row in range(CPC_TILE_ROWS):
            row_words = words[row * 4:(row + 1) * 4]
            word_str = ",".join(f"${w:04X}" for w in row_words)
            lines.append(f"        dc.w    {word_str}")

    lines.append("")
    lines.append(f"TILE_COUNT equ {tile_count}")
    lines.append("")

    # Single mask table
    lines.append("; Per-tile transparency masks (single table, all 256 tiles)")
    lines.append(f"; {tile_count} tiles x 64 bytes = {tile_count * 64} bytes")
    lines.append("; Mask word: $0000 = opaque, $FFFF = fully transparent")
    lines.append("tile_masks:")
    for t in range(tile_count):
        lines.append(f"; Tile {t} masks")
        masks = tile_masks[t]
        for row in range(CPC_TILE_ROWS):
            row_masks = masks[row * 4:(row + 1) * 4]
            word_str = ",".join(f"${w:04X}" for w in row_masks)
            lines.append(f"        dc.w    {word_str}")

    lines.append("")
    lines.append("        even")
    lines.append("")

    return "\n".join(lines)


def generate_preview(tile_count, ql_tiles, palette_map, output_path):
    """Generate PNG preview of all tiles in a grid."""
    try:
        from PIL import Image
    except ImportError:
        print("  Skipping preview (PIL/Pillow not installed)")
        return

    ql_rgb = {name: rgb for name, rgb in cpc_utils.QL_COLOURS.items()}

    cols = 16
    rows = (tile_count + cols - 1) // cols
    tile_w, tile_h = 16, 8
    padding = 1
    img_w = cols * (tile_w + padding) + padding
    img_h = rows * (tile_h + padding) + padding

    img = Image.new("RGB", (img_w, img_h), (64, 64, 64))

    for t in range(tile_count):
        col = t % cols
        row = t // cols
        x0 = col * (tile_w + padding) + padding
        y0 = row * (tile_h + padding) + padding

        words = ql_tiles[t]
        for ty in range(tile_h):
            for wx in range(4):  # 4 words per row
                word = words[ty * 4 + wx]
                hi = (word >> 8) & 0xFF
                lo = word & 0xFF
                for px in range(4):
                    shift = 6 - px * 2
                    g = (hi >> shift) & 3
                    f = (lo >> shift) & 3
                    # Map G/F bits to RGB
                    green = 255 if (g & 2) else 0  # g bit 1 = Green
                    r = 255 if (f & 2) else 0      # f bit 1 = Red
                    b = 255 if (f & 1) else 0      # f bit 0 = Blue
                    x = x0 + wx * 4 + px
                    y = y0 + ty
                    if x < img_w and y < img_h:
                        img.putpixel((x, y), (r, green, b))

    # Scale up 4x for visibility
    img = img.resize((img_w * 4, img_h * 4), Image.NEAREST)
    img.save(output_path)
    print(f"  Preview saved: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Convert CPC tiles to QL Mode 8")
    parser.add_argument("--palette", type=str, default=None,
                        help="4 CPC HW colour values: ink0,ink1,ink2,ink3 (hex)")
    parser.add_argument("--input", type=str, default=os.path.join(DATA_DIR, "ABADIA3.BIN"))
    parser.add_argument("--output", type=str, default=os.path.join(SRC_DIR, "tile_data.s"))
    parser.add_argument("--no-preview", action="store_true")
    args = parser.parse_args()

    if args.palette:
        palette_hw = cpc_utils.parse_palette_arg(args.palette)
    else:
        palette_hw = None  # use defaults + overrides

    if not os.path.exists(args.input):
        print(f"Error: {args.input} not found", file=sys.stderr)
        print("Run extract_cpc.py first.", file=sys.stderr)
        sys.exit(1)

    with open(args.input, "rb") as f:
        bin_data = f.read()

    palette_map = cpc_utils.build_palette_map(palette_hw)
    hw_values = palette_hw if palette_hw else cpc_utils.DEFAULT_PALETTE_HW
    print(f"Palette: {palette_map}")

    # Extract tile data
    tile_data = bin_data[TILE_DATA_OFFSET:TILE_DATA_OFFSET + TILE_DATA_SIZE]
    tile_count = NUM_TILES
    non_empty = count_tiles(tile_data)
    print(f"Tile data: {len(tile_data)} bytes, {non_empty} non-empty of {tile_count} tiles")

    # Convert all 256 tiles
    ql_tiles = []
    for t in range(tile_count):
        offset = t * CPC_TILE_BYTES
        tile_bytes = tile_data[offset:offset + CPC_TILE_BYTES]
        ql_words = convert_tile(tile_bytes, palette_map)
        ql_tiles.append(ql_words)

    # Compute per-tile transparent colours matching CPC mask tables ($3AD1):
    # Verified by tracing Z80 code: nibble-swap algorithm at $3AD1-$3B12
    #   Table 1 ($9D00/$9E00) used for tiles 0-127:   ink 1 is transparent
    #   Table 2 ($9F00/$A000) used for tiles 128-255: ink 2 is transparent
    # Selection: BIT 7,C at $4F4C; Z→$9D (tiles 0-127), NZ→$9F (tiles 128-255)
    trans_colour_lo = cpc_utils.QL_COLOUR_WORDS[palette_map[1]]  # ink 1 for tiles 0-127
    trans_colour_hi = cpc_utils.QL_COLOUR_WORDS[palette_map[2]]  # ink 2 for tiles 128-255
    transparent_colours = []
    for t in range(tile_count):
        if t < 128:
            transparent_colours.append(trans_colour_lo)
        else:
            transparent_colours.append(trans_colour_hi)
    tile_masks = compute_per_tile_masks_from_pixels(tile_count, ql_tiles, transparent_colours)

    # Zero out tile data at transparent positions so OR doesn't corrupt buffer.
    # CPC mask tables zero the colour output for transparent pixels automatically.
    for t in range(tile_count):
        for i in range(len(ql_tiles[t])):
            ql_tiles[t][i] &= (~tile_masks[t][i]) & 0xFFFF

    print(f"Masks: tiles 0-127 trans=${trans_colour_lo:04X} (ink 1), "
          f"tiles 128-255 trans=${trans_colour_hi:04X} (ink 2)")

    # Generate assembly output
    asm = generate_assembly(tile_count, ql_tiles, tile_masks)
    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", newline="\n") as f:
        f.write(asm)
    print(f"Output: {args.output}")

    # Generate preview
    if not args.no_preview:
        preview_path = os.path.join(DATA_DIR, "tiles_preview.png")
        generate_preview(tile_count, ql_tiles, palette_map, preview_path)


if __name__ == "__main__":
    main()
