#!/usr/bin/env python3
"""One-shot import of the fork's parchment sources into cpp/vigasoco:
Pergamino.cpp/.h and alphabet.h (UTF-8/LF like import_vigasoco.py), and a trimmed
PergaminoTextos.cpp holding only pergaminoInicio and pergaminoFinal in Spanish (0) and
English (1). The texts index the parchment font by byte value, so the Latin-1 bytes of the
original strings are written as octal escapes (the generated file is pure ASCII).
Refuses to overwrite unless --force."""
import argparse, os, re, sys
import qlpaths  # local tool paths (tools/qlpaths.py)

SRC = qlpaths.ABBEY_VIGASOCO
DST = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "cpp", "vigasoco")


def decode(b):
    try:
        return b.decode("utf-8")
    except UnicodeDecodeError:
        return b.decode("latin-1")


def literals(region):
    """C string literals in region (latin-1 text), as lists of source pieces."""
    out = []
    for m in re.finditer(r'"((?:[^"\\]|\\.)*)"', region):
        body = m.group(1)
        esc = []
        for ch in body:
            o = ord(ch)
            esc.append(ch if o < 128 else "\\%03o" % o)
        out.append("".join(esc))
    return out


def language_blocks(arr_text):
    """Split an array initialiser into its 8 language entries by the '(const unsigned char*)' casts."""
    parts = re.split(r"\(const unsigned char\s*\*\)", arr_text)
    return parts[1:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args()
    for name in ("Pergamino.cpp", "Pergamino.h", "alphabet.h"):
        dp = os.path.join(DST, name)
        if os.path.exists(dp) and not a.force:
            print("exists, skipped:", name)
            continue
        txt = decode(open(os.path.join(SRC, name), "rb").read()).replace("\r\n", "\n")
        open(dp, "w", encoding="utf-8", newline="\n").write(txt)
    dp = os.path.join(DST, "PergaminoTextos.cpp")
    if os.path.exists(dp) and not a.force:
        print("exists, skipped: PergaminoTextos.cpp")
        return 0
    src = open(os.path.join(SRC, "PergaminoTextos.cpp"), "rb").read().decode("latin-1").replace("\r\n", "\n")
    out = ["// PergaminoTextos.cpp -- QL: generated by tools/import_pergamino.py from the fork's file.",
           "// Only the start and end parchments, Spanish (0) and English (1); Latin-1 bytes as octal",
           "// escapes (they index the parchment font). See CREDITS.txt.",
           "", '#include "Pergamino.h"', "", "using namespace Abadia;", ""]
    for arr in ("pergaminoInicio", "pergaminoFinal"):
        m = re.search(r"\nconst unsigned char \* Pergamino::%s\[8\]\s*=" % arr, src)
        assert m, arr
        start = m.end()
        end = src.index("};", start)
        blocks = language_blocks(src[start:end])
        assert len(blocks) == 8, (arr, len(blocks))
        out.append("const unsigned char * Pergamino::%s[QL_NUM_IDIOMAS] = {" % arr)
        for i in (0, 1):
            lits = literals(blocks[i])
            assert lits, (arr, i)
            out.append("\t// %s" % ("Spanish" if i == 0 else "English"))
            out.append("\t(const unsigned char*)")
            for l in lits:
                out.append('\t"%s"' % l)
            out.append("\t,")
        out.append("};")
        out.append("")
    open(dp, "w", encoding="ascii", newline="\n").write("\n".join(out) + "\n")
    print("wrote", dp)
    return 0


if __name__ == "__main__":
    sys.exit(main())
