#!/usr/bin/env python3
"""audio/dos/<name>_ql.json -> cpp/port/ql_beeps_data.h (QL beeper sequencer tables).

Each sound becomes a list of {frame, 8 IPC parameter bytes} in issue order, plus the frame at
which its last BEEP has finished sounding (its "end"), which is when an effect stops owning the
beeper. The parchment tune also gets its loop length in frames (one DOS pass).

  mkbeeps.py            writes the header
  mkbeeps.py --check    exits 1 if the header is out of date
"""
import json, math, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
QL = os.path.dirname(HERE)
SRC = os.path.join(QL, "audio", "dos")
OUT = os.path.join(QL, "cpp", "port", "ql_beeps_data.h")
TICK_HZ = 22917.0
FRAME_TICKS = TICK_HZ / 50.0

# order = the effect index the C uses (SOUNDFILES ids, then SPEECH = 9)
EFFECTS = ["open_door", "hit", "bells", "close", "get", "let", "mirror", "steps", "jingle", "speech"]
MUSIC = "music_parchment"


def load(name):
    with open(os.path.join(SRC, name + "_ql.json")) as f:
        return json.load(f)


def beeps_of(d):
    out = []
    for b in d["beeps"]:
        bb = b["ipc_bytes"]
        assert len(bb) == 8 and all(0 <= x < 256 for x in bb), (d["name"], bb)
        out.append((int(b["frame"]), bb))
    frames = [f for f, _ in out]
    assert frames == sorted(frames), d["name"]
    return out


def end_frame(beeps):
    """frame by which every BEEP has finished: max(onset + duration)"""
    e = 0
    for f, bb in beeps:
        dur = bb[4] | ((bb[5] & 0x7F) << 8)
        e = max(e, f + int(math.ceil(dur / FRAME_TICKS)))
    return e


def emit():
    lines = ["/* ql_beeps_data.h -- GENERATED by tools/mkbeeps.py from audio/dos/*_ql.json. Do not edit. */",
             "#ifndef QL_BEEPS_DATA_H", "#define QL_BEEPS_DATA_H", "",
             "/* one BEEP: issue frame after the trigger, then the 8 IPC parameter bytes",
             "   (p1, p2, interval LE, duration LE, step|wrap, random|fuzz) */",
             "typedef struct { unsigned short frame; unsigned char b[8]; } QlBeep;",
             "typedef struct { const QlBeep *list; unsigned short n; unsigned short end; } QlBeepSound;", ""]
    for name in EFFECTS + [MUSIC]:
        bl = beeps_of(load(name))
        lines.append("static const QlBeep qb_%s[%d] = {" % (name, len(bl)))
        for f, bb in bl:
            lines.append("\t{ %d, { %s } }," % (f, ", ".join("0x%02X" % x for x in bb)))
        lines.append("};")
    lines.append("")
    lines.append("/* effects, indexed by SOUNDFILES id (OPEN, HIT, BELLS, CLOSE, GET, LET, MIRROR, STEPS, JINGLE), SPEECH = 9 */")
    lines.append("static const QlBeepSound qb_effects[%d] = {" % len(EFFECTS))
    for name in EFFECTS:
        bl = beeps_of(load(name))
        lines.append("\t{ qb_%s, %d, %d },\t/* %s */" % (name, len(bl), end_frame(bl), name))
    lines.append("};")
    m = load(MUSIC)
    src = json.load(open(os.path.join(SRC, MUSIC + ".json")))
    loop = int(round(src["pass_ms"] / 20.0))
    mb = beeps_of(m)
    assert mb[-1][0] < loop, (mb[-1][0], loop)
    lines.append("")
    lines.append("/* the parchment tune (DOS C1A8, -1 octave); loops every QB_MUSIC_LOOP frames (one DOS pass, %.1f ms) */" % src["pass_ms"])
    lines.append("#define QB_MUSIC_LOOP %d" % loop)
    lines.append("static const QlBeepSound qb_music = { qb_%s, %d, %d };" % (MUSIC, len(mb), loop))
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def main():
    text = emit()
    if "--check" in sys.argv:
        old = open(OUT).read() if os.path.exists(OUT) else ""
        if old.replace("\r\n", "\n") != text:       # git may check it out with CRLF
            print("ql_beeps_data.h is out of date: run tools/mkbeeps.py")
            return 1
        print("ql_beeps_data.h up to date")
        return 0
    open(OUT, "w", newline="\n").write(text)
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
