#!/usr/bin/env python3
"""data/colour_mapping.json (exported by tools/colour_mapper.html) -> src/palette_data.s, the
QL colour tables the game uses. Run by build_hybrid.sh before vasm.

JSON: {"palettes": {"0".."3": {"terrain": [c0, c1, c2, c3], "characters": [...], "panel": [...],
"lamp": [...]}}}; a colour is a QL colour name, or a pair [a, b] for a 2x2 checker dither
(pixel (x, y) of the QL screen shows a when x + y is even, b when odd; as the tool draws it).

What the game shows (CHARCOL, qlhooks.s):
  - terrain: tiles, room fills, the parchment and everything not below, with dithers;
  - characters: every pixel the sprite mixer draws from a sprite (monks, Guillermo, Adso,
    objects, doors, reflections), with dithers; only built for a palette whose characters row
    differs from its terrain row (otherwise no mask work at all);
  - panel: the HUD under the play area, with dithers;
  - lamp: SpriteLuz only writes pen 3 and the game shows it with the TERRAIN pen 3: a lamp row
    whose pen 3 differs from terrain pen 3 is reported (the other lamp pens are never drawn).
  - palettes 0 and 1 never show sprites or the panel (black screen / full-screen parchment):
    their characters and panel rows are accepted but unused, and reported as such.

Output (64 bytes per palette, pal_table): terrain even-line words, terrain odd-line words,
characters even, characters odd, panel even, panel odd (4 Mode 8 colour words each), then a
flags word (bit 0: characters row differs from terrain), padding. Also `palettes:` (terrain
even words, 4 per palette) for the pre-CHARCOL code that stays assembled out.

  mkpalette.py [--check]     --check: exit 1 if src/palette_data.s is out of date
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
QL = os.path.dirname(HERE)
SRC = os.path.join(QL, "data", "colour_mapping.json")
OUT = os.path.join(QL, "src", "palette_data.s")
OUT_JS = os.path.join(HERE, "colour_mapping_build.js")     # the build's mapping, for tools/colour_mapper.html
NAMES = ["black", "blue", "red", "magenta", "green", "cyan", "yellow", "white"]
# Mode 8 colour words (equates.s COL_*): all four pixels of a word in one colour
WORD = {"black": 0x0000, "blue": 0x0055, "red": 0x00AA, "magenta": 0x00FF,
        "green": 0xAA00, "cyan": 0xAA55, "yellow": 0xAAAA, "white": 0xAAFF}
PIX = [0xC0C0, 0x3030, 0x0C0C, 0x0303]            # pixel 0..3 of a Mode 8 word (screen.s pixel_masks)
PAL_NAMES = {0: "black", 1: "parchment", 2: "day", 3: "night"}
CLASSES = ("terrain", "characters", "panel")


def words(c):
    """even-line and odd-line Mode 8 words for colour c (a name or a dither pair)"""
    if isinstance(c, list):
        assert len(c) == 2 and all(x in NAMES for x in c), c
        a, b = WORD[c[0]], WORD[c[1]]
    else:
        assert c in NAMES, c
        a = b = WORD[c]
    even = (a & (PIX[0] | PIX[2])) | (b & (PIX[1] | PIX[3]))     # x even -> a
    odd = (b & (PIX[0] | PIX[2])) | (a & (PIX[1] | PIX[3]))      # x even -> b
    return even, odd


def emit(m):
    notes = []
    lines = ["; ============================================================",
             "; palette_data.s - GENERATED by tools/mkpalette.py from data/colour_mapping.json",
             "; (edit the mapping with tools/colour_mapper.html, not this file)",
             "; CPC palettes 0 black, 1 parchment, 2 day, 3 night -> QL Mode 8 colour words, pens 0-3.",
             "; pal_table, 64 bytes a palette: terrain even/odd lines, characters even/odd,",
             "; panel even/odd (4 words each), flags word (bit 0: characters differ), padding.",
             "; ============================================================",
             "        cnop    0,2",
             "pal_table:"]
    old = []
    for p in range(4):
        e = m["palettes"][str(p)]
        rows = {}
        for cls in CLASSES:
            pens = e.get(cls, e["terrain"]) if p not in (0, 1) else e["terrain"]   # 0/1: unused rows
            assert len(pens) == 4, (p, cls)
            rows[cls] = [words(c) for c in pens]
        sep = e.get("characters", e["terrain"]) != e["terrain"]
        if p in (0, 1):
            for cls in ("characters", "panel"):
                if e.get(cls, e["terrain"]) != e["terrain"]:
                    notes.append("palette %d (%s): %s row unused (no sprites or panel are drawn under this "
                                 "palette)" % (p, PAL_NAMES[p], cls))
            sep = False
        lamp = e.get("lamp", e["terrain"])
        if lamp[3] != e["terrain"][3]:
            notes.append("palette %d (%s): lamp pen 3 %r differs from terrain pen 3 %r: NOT shown (the lamp's dark "
                         "pixels use the terrain pen 3; a lamp class would need a second mask)"
                         % (p, PAL_NAMES[p], lamp[3], e["terrain"][3]))
        lines.append("        ; %d %s%s" % (p, PAL_NAMES[p], " (separate character colours)" if sep else ""))
        for cls in CLASSES:
            for par, label in ((0, "even"), (1, "odd")):
                lines.append("        dc.w    %s   ; %s %s lines" % (
                    ",".join("$%04X" % w[par] for w in rows[cls]), cls, label))
        lines.append("        dc.w    %d   ; flags" % (1 if sep else 0))
        lines.append("        ds.w    7")
        old.append(rows["terrain"])
    lines.append("")
    lines.append("; the pre-CHARCOL table (terrain even-line words), for the code kept assembled out")
    lines.append("palettes:")
    for p in range(4):
        lines.append("        dc.w    %s   ; %d %s" % (",".join("$%04X" % w[0] for w in old[p]), p, PAL_NAMES[p]))
    lines.append("")
    return "\n".join(lines), notes


def main():
    m = json.load(open(SRC))
    text, notes = emit(m)
    for n in notes:
        print("mkpalette: " + n)
    old = open(OUT).read().replace("\r\n", "\n") if os.path.exists(OUT) else ""
    js = ("// GENERATED by tools/mkpalette.py from data/colour_mapping.json: the mapping the build uses.\n"
          "var COLOUR_MAPPING_BUILD = " + json.dumps(m["palettes"]) + ";\n")
    oldjs = open(OUT_JS).read().replace("\r\n", "\n") if os.path.exists(OUT_JS) else ""
    if "--check" in sys.argv:
        if old != text or oldjs != js:
            print("src/palette_data.s is out of date: run tools/mkpalette.py")
            return 1
        print("palette_data.s up to date")
        return 0
    if old != text:
        open(OUT, "w", newline="\n").write(text)
        print("mkpalette: wrote src/palette_data.s")
    if oldjs != js:
        open(OUT_JS, "w", newline="\n").write(js)
        print("mkpalette: wrote tools/colour_mapping_build.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
