; ============================================================
; object_types.s - Object type rendering data
; Generated by simulate_renderer.py - DO NOT EDIT
;
; obj_type_offsets: word offset table (indexed by type_byte/2)
; obj_type_data:   variable-length entries
;   Each entry: dc.b num_sub_tiles
;     Followed by: dc.b dH, dL, tile_index  (per sub-tile)
;   dH/dL are SIGNED byte offsets from object grid position
; ============================================================

OBJ_TYPE_COUNT equ 80

obj_type_offsets:
        dc.w    0,1,8,15,22,29,39,49
        dc.w    59,69,79,89,108,127,143,159
        dc.w    175,191,240,289,362,441,448,455
        dc.w    480,505,530,555,562,578,603,640
        dc.w    680,720,736,737,744,763,770,789
        dc.w    835,845,855,862,863,879,895,923
        dc.w    951,964,977,1023,1042,1055,1056,1075
        dc.w    1094,1119,1144,1169,1185,1201,1217,1224
        dc.w    1237,1250,1260,1270,1334,1401,1432,1463
        dc.w    1476,1489,1505,1545,1549,1556,1566,1582

obj_type_data:
; type $00 (unused (Invalid pointer $0000))
        dc.b    0
; type $02 (2 sub-tiles)
        dc.b    2
        dc.b    0,0,40  ; dH=+0 dL=+0 tile=40
        dc.b    255,0,41  ; dH=-1 dL=+0 tile=41
; type $04 (2 sub-tiles)
        dc.b    2
        dc.b    0,0,42  ; dH=+0 dL=+0 tile=42
        dc.b    255,0,45  ; dH=-1 dL=+0 tile=45
; type $06 (2 sub-tiles)
        dc.b    2
        dc.b    0,0,98  ; dH=+0 dL=+0 tile=98
        dc.b    255,0,99  ; dH=-1 dL=+0 tile=99
; type $08 (2 sub-tiles)
        dc.b    2
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,116  ; dH=-1 dL=+0 tile=116
; type $0A (3 sub-tiles)
        dc.b    3
        dc.b    0,0,35  ; dH=+0 dL=+0 tile=35
        dc.b    255,0,33  ; dH=-1 dL=+0 tile=33
        dc.b    254,0,41  ; dH=-2 dL=+0 tile=41
; type $0C (3 sub-tiles)
        dc.b    3
        dc.b    0,0,37  ; dH=+0 dL=+0 tile=37
        dc.b    255,0,36  ; dH=-1 dL=+0 tile=36
        dc.b    254,0,45  ; dH=-2 dL=+0 tile=45
; type $0E (3 sub-tiles)
        dc.b    3
        dc.b    0,0,55  ; dH=+0 dL=+0 tile=55
        dc.b    255,0,53  ; dH=-1 dL=+0 tile=53
        dc.b    254,0,53  ; dH=-2 dL=+0 tile=53
; type $10 (3 sub-tiles)
        dc.b    3
        dc.b    0,0,51  ; dH=+0 dL=+0 tile=51
        dc.b    255,0,51  ; dH=-1 dL=+0 tile=51
        dc.b    254,0,50  ; dH=-2 dL=+0 tile=50
; type $12 (3 sub-tiles)
        dc.b    3
        dc.b    0,0,153  ; dH=+0 dL=+0 tile=153
        dc.b    255,0,151  ; dH=-1 dL=+0 tile=151
        dc.b    254,0,152  ; dH=-2 dL=+0 tile=152
; type $14 (3 sub-tiles)
        dc.b    3
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,151  ; dH=-1 dL=+0 tile=151
        dc.b    254,0,152  ; dH=-2 dL=+0 tile=152
; type $16 (6 sub-tiles)
        dc.b    6
        dc.b    0,0,16  ; dH=+0 dL=+0 tile=16
        dc.b    255,0,19  ; dH=-1 dL=+0 tile=19
        dc.b    0,255,178  ; dH=+0 dL=-1 tile=178
        dc.b    255,255,179  ; dH=-1 dL=-1 tile=179
        dc.b    254,255,177  ; dH=-2 dL=-1 tile=177
        dc.b    254,0,69  ; dH=-2 dL=+0 tile=69
; type $18 (6 sub-tiles)
        dc.b    6
        dc.b    0,0,15  ; dH=+0 dL=+0 tile=15
        dc.b    255,0,17  ; dH=-1 dL=+0 tile=17
        dc.b    0,1,129  ; dH=+0 dL=+1 tile=129
        dc.b    255,1,130  ; dH=-1 dL=+1 tile=130
        dc.b    254,1,128  ; dH=-2 dL=+1 tile=128
        dc.b    254,0,68  ; dH=-2 dL=+0 tile=68
; type $1A (5 sub-tiles)
        dc.b    5
        dc.b    0,0,2  ; dH=+0 dL=+0 tile=2
        dc.b    255,0,2  ; dH=-1 dL=+0 tile=2
        dc.b    255,1,2  ; dH=-1 dL=+1 tile=2
        dc.b    254,1,1  ; dH=-2 dL=+1 tile=1
        dc.b    254,0,4  ; dH=-2 dL=+0 tile=4
; type $1C (5 sub-tiles)
        dc.b    5
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,1,0  ; dH=-1 dL=+1 tile=0
        dc.b    254,1,75  ; dH=-2 dL=+1 tile=75
        dc.b    254,0,77  ; dH=-2 dL=+0 tile=77
; type $1E (5 sub-tiles)
        dc.b    5
        dc.b    0,0,3  ; dH=+0 dL=+0 tile=3
        dc.b    255,0,3  ; dH=-1 dL=+0 tile=3
        dc.b    255,1,3  ; dH=-1 dL=+1 tile=3
        dc.b    254,1,76  ; dH=-2 dL=+1 tile=76
        dc.b    254,0,89  ; dH=-2 dL=+0 tile=89
; type $20 (5 sub-tiles)
        dc.b    5
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,1,0  ; dH=-1 dL=+1 tile=0
        dc.b    254,1,0  ; dH=-2 dL=+1 tile=0
        dc.b    254,0,207  ; dH=-2 dL=+0 tile=207
; type $22 (16 sub-tiles)
        dc.b    16
        dc.b    0,0,155  ; dH=+0 dL=+0 tile=155
        dc.b    255,0,251  ; dH=-1 dL=+0 tile=251
        dc.b    254,0,200  ; dH=-2 dL=+0 tile=200
        dc.b    253,0,197  ; dH=-3 dL=+0 tile=197
        dc.b    252,0,198  ; dH=-4 dL=+0 tile=198
        dc.b    251,0,199  ; dH=-5 dL=+0 tile=199
        dc.b    253,1,0  ; dH=-3 dL=+1 tile=0
        dc.b    252,1,0  ; dH=-4 dL=+1 tile=0
        dc.b    251,1,194  ; dH=-5 dL=+1 tile=194
        dc.b    250,1,192  ; dH=-6 dL=+1 tile=192
        dc.b    251,2,193  ; dH=-5 dL=+2 tile=193
        dc.b    250,2,191  ; dH=-6 dL=+2 tile=191
        dc.b    253,3,155  ; dH=-3 dL=+3 tile=155
        dc.b    252,3,188  ; dH=-4 dL=+3 tile=188
        dc.b    251,3,189  ; dH=-5 dL=+3 tile=189
        dc.b    250,3,190  ; dH=-6 dL=+3 tile=190
; type $24 (16 sub-tiles)
        dc.b    16
        dc.b    0,0,155  ; dH=+0 dL=+0 tile=155
        dc.b    255,0,251  ; dH=-1 dL=+0 tile=251
        dc.b    254,0,247  ; dH=-2 dL=+0 tile=247
        dc.b    253,0,248  ; dH=-3 dL=+0 tile=248
        dc.b    252,0,249  ; dH=-4 dL=+0 tile=249
        dc.b    251,0,250  ; dH=-5 dL=+0 tile=250
        dc.b    253,255,0  ; dH=-3 dL=-1 tile=0
        dc.b    252,255,0  ; dH=-4 dL=-1 tile=0
        dc.b    251,255,244  ; dH=-5 dL=-1 tile=244
        dc.b    250,255,242  ; dH=-6 dL=-1 tile=242
        dc.b    251,254,243  ; dH=-5 dL=-2 tile=243
        dc.b    250,254,241  ; dH=-6 dL=-2 tile=241
        dc.b    253,253,155  ; dH=-3 dL=-3 tile=155
        dc.b    252,253,238  ; dH=-4 dL=-3 tile=238
        dc.b    251,253,239  ; dH=-5 dL=-3 tile=239
        dc.b    250,253,240  ; dH=-6 dL=-3 tile=240
; type $26 (24 sub-tiles)
        dc.b    24
        dc.b    0,1,155  ; dH=+0 dL=+1 tile=155
        dc.b    255,1,251  ; dH=-1 dL=+1 tile=251
        dc.b    254,1,200  ; dH=-2 dL=+1 tile=200
        dc.b    253,1,197  ; dH=-3 dL=+1 tile=197
        dc.b    252,1,198  ; dH=-4 dL=+1 tile=198
        dc.b    251,1,199  ; dH=-5 dL=+1 tile=199
        dc.b    253,2,0  ; dH=-3 dL=+2 tile=0
        dc.b    252,2,0  ; dH=-4 dL=+2 tile=0
        dc.b    251,2,194  ; dH=-5 dL=+2 tile=194
        dc.b    250,2,192  ; dH=-6 dL=+2 tile=192
        dc.b    251,3,193  ; dH=-5 dL=+3 tile=193
        dc.b    250,3,191  ; dH=-6 dL=+3 tile=191
        dc.b    253,4,155  ; dH=-3 dL=+4 tile=155
        dc.b    252,4,188  ; dH=-4 dL=+4 tile=188
        dc.b    251,4,189  ; dH=-5 dL=+4 tile=189
        dc.b    250,4,190  ; dH=-6 dL=+4 tile=190
        dc.b    0,1,153  ; dH=+0 dL=+1 tile=153
        dc.b    255,1,0  ; dH=-1 dL=+1 tile=0
        dc.b    254,1,0  ; dH=-2 dL=+1 tile=0
        dc.b    253,1,0  ; dH=-3 dL=+1 tile=0
        dc.b    252,1,151  ; dH=-4 dL=+1 tile=151
        dc.b    250,1,153  ; dH=-6 dL=+1 tile=153
        dc.b    249,1,0  ; dH=-7 dL=+1 tile=0
        dc.b    248,1,0  ; dH=-8 dL=+1 tile=0
; type $28 (26 sub-tiles)
        dc.b    26
        dc.b    0,1,155  ; dH=+0 dL=+1 tile=155
        dc.b    255,1,251  ; dH=-1 dL=+1 tile=251
        dc.b    254,1,247  ; dH=-2 dL=+1 tile=247
        dc.b    253,1,248  ; dH=-3 dL=+1 tile=248
        dc.b    252,1,249  ; dH=-4 dL=+1 tile=249
        dc.b    251,1,250  ; dH=-5 dL=+1 tile=250
        dc.b    253,0,0  ; dH=-3 dL=+0 tile=0
        dc.b    252,0,0  ; dH=-4 dL=+0 tile=0
        dc.b    251,0,244  ; dH=-5 dL=+0 tile=244
        dc.b    250,0,242  ; dH=-6 dL=+0 tile=242
        dc.b    251,255,243  ; dH=-5 dL=-1 tile=243
        dc.b    250,255,241  ; dH=-6 dL=-1 tile=241
        dc.b    253,254,155  ; dH=-3 dL=-2 tile=155
        dc.b    252,254,238  ; dH=-4 dL=-2 tile=238
        dc.b    251,254,239  ; dH=-5 dL=-2 tile=239
        dc.b    250,254,240  ; dH=-6 dL=-2 tile=240
        dc.b    0,1,0  ; dH=+0 dL=+1 tile=0
        dc.b    255,1,154  ; dH=-1 dL=+1 tile=154
        dc.b    254,1,154  ; dH=-2 dL=+1 tile=154
        dc.b    253,1,154  ; dH=-3 dL=+1 tile=154
        dc.b    252,1,151  ; dH=-4 dL=+1 tile=151
        dc.b    0,251,0  ; dH=+0 dL=-5 tile=0
        dc.b    255,251,154  ; dH=-1 dL=-5 tile=154
        dc.b    254,251,154  ; dH=-2 dL=-5 tile=154
        dc.b    253,251,154  ; dH=-3 dL=-5 tile=154
        dc.b    252,251,151  ; dH=-4 dL=-5 tile=151
; type $2A (2 sub-tiles)
        dc.b    2
        dc.b    0,0,170  ; dH=+0 dL=+0 tile=170
        dc.b    255,0,171  ; dH=-1 dL=+0 tile=171
; type $2C (2 sub-tiles)
        dc.b    2
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,168  ; dH=-1 dL=+0 tile=168
; type $2E (8 sub-tiles)
        dc.b    8
        dc.b    0,0,40  ; dH=+0 dL=+0 tile=40
        dc.b    255,0,6  ; dH=-1 dL=+0 tile=6
        dc.b    255,0,41  ; dH=-1 dL=+0 tile=41
        dc.b    254,0,0  ; dH=-2 dL=+0 tile=0
        dc.b    0,255,43  ; dH=+0 dL=-1 tile=43
        dc.b    255,255,6  ; dH=-1 dL=-1 tile=6
        dc.b    255,255,45  ; dH=-1 dL=-1 tile=45
        dc.b    254,255,117  ; dH=-2 dL=-1 tile=117
; type $30 (8 sub-tiles)
        dc.b    8
        dc.b    0,0,43  ; dH=+0 dL=+0 tile=43
        dc.b    255,0,7  ; dH=-1 dL=+0 tile=7
        dc.b    255,0,45  ; dH=-1 dL=+0 tile=45
        dc.b    254,0,0  ; dH=-2 dL=+0 tile=0
        dc.b    0,1,40  ; dH=+0 dL=+1 tile=40
        dc.b    255,1,7  ; dH=-1 dL=+1 tile=7
        dc.b    255,1,41  ; dH=-1 dL=+1 tile=41
        dc.b    254,1,118  ; dH=-2 dL=+1 tile=118
; type $32 (8 sub-tiles)
        dc.b    8
        dc.b    0,0,216  ; dH=+0 dL=+0 tile=216
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,0,220  ; dH=-1 dL=+0 tile=220
        dc.b    254,0,0  ; dH=-2 dL=+0 tile=0
        dc.b    0,255,215  ; dH=+0 dL=-1 tile=215
        dc.b    255,255,0  ; dH=-1 dL=-1 tile=0
        dc.b    255,255,221  ; dH=-1 dL=-1 tile=221
        dc.b    254,255,218  ; dH=-2 dL=-1 tile=218
; type $34 (8 sub-tiles)
        dc.b    8
        dc.b    0,0,215  ; dH=+0 dL=+0 tile=215
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,0,221  ; dH=-1 dL=+0 tile=221
        dc.b    254,0,0  ; dH=-2 dL=+0 tile=0
        dc.b    0,1,216  ; dH=+0 dL=+1 tile=216
        dc.b    255,1,0  ; dH=-1 dL=+1 tile=0
        dc.b    255,1,220  ; dH=-1 dL=+1 tile=220
        dc.b    254,1,212  ; dH=-2 dL=+1 tile=212
; type $36 (2 sub-tiles)
        dc.b    2
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,125  ; dH=-1 dL=+0 tile=125
; type $38 (5 sub-tiles)
        dc.b    5
        dc.b    0,0,6  ; dH=+0 dL=+0 tile=6
        dc.b    255,0,6  ; dH=-1 dL=+0 tile=6
        dc.b    255,1,6  ; dH=-1 dL=+1 tile=6
        dc.b    254,1,0  ; dH=-2 dL=+1 tile=0
        dc.b    254,0,117  ; dH=-2 dL=+0 tile=117
; type $3A (8 sub-tiles)
        dc.b    8
        dc.b    0,0,63  ; dH=+0 dL=+0 tile=63
        dc.b    255,0,62  ; dH=-1 dL=+0 tile=62
        dc.b    254,0,61  ; dH=-2 dL=+0 tile=61
        dc.b    253,0,63  ; dH=-3 dL=+0 tile=63
        dc.b    1,255,60  ; dH=+1 dL=-1 tile=60
        dc.b    0,255,58  ; dH=+0 dL=-1 tile=58
        dc.b    255,255,57  ; dH=-1 dL=-1 tile=57
        dc.b    254,255,60  ; dH=-2 dL=-1 tile=60
; type $3C (12 sub-tiles)
        dc.b    12
        dc.b    0,0,215  ; dH=+0 dL=+0 tile=215
        dc.b    255,0,221  ; dH=-1 dL=+0 tile=221
        dc.b    254,0,218  ; dH=-2 dL=+0 tile=218
        dc.b    0,1,0  ; dH=+0 dL=+1 tile=0
        dc.b    255,1,220  ; dH=-1 dL=+1 tile=220
        dc.b    254,1,219  ; dH=-2 dL=+1 tile=219
        dc.b    253,1,150  ; dH=-3 dL=+1 tile=150
        dc.b    255,2,0  ; dH=-1 dL=+2 tile=0
        dc.b    254,2,0  ; dH=-2 dL=+2 tile=0
        dc.b    253,2,148  ; dH=-3 dL=+2 tile=148
        dc.b    252,2,234  ; dH=-4 dL=+2 tile=234
        dc.b    251,2,208  ; dH=-5 dL=+2 tile=208
; type $3E (13 sub-tiles)
        dc.b    13
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    254,0,0  ; dH=-2 dL=+0 tile=0
        dc.b    253,0,163  ; dH=-3 dL=+0 tile=163
        dc.b    252,0,161  ; dH=-4 dL=+0 tile=161
        dc.b    251,0,159  ; dH=-5 dL=+0 tile=159
        dc.b    250,0,157  ; dH=-6 dL=+0 tile=157
        dc.b    255,1,166  ; dH=-1 dL=+1 tile=166
        dc.b    254,1,164  ; dH=-2 dL=+1 tile=164
        dc.b    253,1,164  ; dH=-3 dL=+1 tile=164
        dc.b    252,1,162  ; dH=-4 dL=+1 tile=162
        dc.b    251,1,160  ; dH=-5 dL=+1 tile=160
        dc.b    250,1,158  ; dH=-6 dL=+1 tile=158
; type $40 (13 sub-tiles)
        dc.b    13
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    254,0,0  ; dH=-2 dL=+0 tile=0
        dc.b    253,0,143  ; dH=-3 dL=+0 tile=143
        dc.b    252,0,141  ; dH=-4 dL=+0 tile=141
        dc.b    251,0,139  ; dH=-5 dL=+0 tile=139
        dc.b    250,0,137  ; dH=-6 dL=+0 tile=137
        dc.b    255,255,146  ; dH=-1 dL=-1 tile=146
        dc.b    254,255,144  ; dH=-2 dL=-1 tile=144
        dc.b    253,255,144  ; dH=-3 dL=-1 tile=144
        dc.b    252,255,142  ; dH=-4 dL=-1 tile=142
        dc.b    251,255,140  ; dH=-5 dL=-1 tile=140
        dc.b    250,255,138  ; dH=-6 dL=-1 tile=138
; type $42 (5 sub-tiles)
        dc.b    5
        dc.b    0,0,94  ; dH=+0 dL=+0 tile=94
        dc.b    255,0,203  ; dH=-1 dL=+0 tile=203
        dc.b    254,0,205  ; dH=-2 dL=+0 tile=205
        dc.b    253,0,202  ; dH=-3 dL=+0 tile=202
        dc.b    252,0,70  ; dH=-4 dL=+0 tile=70
; type $44 (unused)
        dc.b    0
; type $46 (2 sub-tiles)
        dc.b    2
        dc.b    0,0,214  ; dH=+0 dL=+0 tile=214
        dc.b    255,0,171  ; dH=-1 dL=+0 tile=171
; type $48 (6 sub-tiles)
        dc.b    6
        dc.b    0,1,55  ; dH=+0 dL=+1 tile=55
        dc.b    255,1,53  ; dH=-1 dL=+1 tile=53
        dc.b    254,1,53  ; dH=-2 dL=+1 tile=53
        dc.b    1,0,51  ; dH=+1 dL=+0 tile=51
        dc.b    0,0,51  ; dH=+0 dL=+0 tile=51
        dc.b    255,0,50  ; dH=-1 dL=+0 tile=50
; type $4A (2 sub-tiles)
        dc.b    2
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,168  ; dH=-1 dL=+0 tile=168
; type $4C (6 sub-tiles)
        dc.b    6
        dc.b    0,1,55  ; dH=+0 dL=+1 tile=55
        dc.b    255,1,53  ; dH=-1 dL=+1 tile=53
        dc.b    254,1,53  ; dH=-2 dL=+1 tile=53
        dc.b    255,2,51  ; dH=-1 dL=+2 tile=51
        dc.b    254,2,51  ; dH=-2 dL=+2 tile=51
        dc.b    253,2,50  ; dH=-3 dL=+2 tile=50
; type $4E (15 sub-tiles)
        dc.b    15
        dc.b    255,254,42  ; dH=-1 dL=-2 tile=42
        dc.b    254,254,10  ; dH=-2 dL=-2 tile=10
        dc.b    253,254,10  ; dH=-3 dL=-2 tile=10
        dc.b    252,254,10  ; dH=-4 dL=-2 tile=10
        dc.b    251,254,10  ; dH=-5 dL=-2 tile=10
        dc.b    250,254,90  ; dH=-6 dL=-2 tile=90
        dc.b    0,0,114  ; dH=+0 dL=+0 tile=114
        dc.b    255,0,113  ; dH=-1 dL=+0 tile=113
        dc.b    254,0,113  ; dH=-2 dL=+0 tile=113
        dc.b    253,0,113  ; dH=-3 dL=+0 tile=113
        dc.b    252,0,113  ; dH=-4 dL=+0 tile=113
        dc.b    251,0,112  ; dH=-5 dL=+0 tile=112
        dc.b    250,0,111  ; dH=-6 dL=+0 tile=111
        dc.b    250,255,110  ; dH=-6 dL=-1 tile=110
        dc.b    249,255,10  ; dH=-7 dL=-1 tile=10
; type $50 (3 sub-tiles)
        dc.b    3
        dc.b    0,0,35  ; dH=+0 dL=+0 tile=35
        dc.b    255,0,97  ; dH=-1 dL=+0 tile=97
        dc.b    254,0,41  ; dH=-2 dL=+0 tile=41
; type $52 (3 sub-tiles)
        dc.b    3
        dc.b    0,0,37  ; dH=+0 dL=+0 tile=37
        dc.b    255,0,39  ; dH=-1 dL=+0 tile=39
        dc.b    254,0,45  ; dH=-2 dL=+0 tile=45
; type $54 (2 sub-tiles)
        dc.b    2
        dc.b    0,0,42  ; dH=+0 dL=+0 tile=42
        dc.b    255,0,44  ; dH=-1 dL=+0 tile=44
; type $56 (unused)
        dc.b    0
; type $58 (5 sub-tiles)
        dc.b    5
        dc.b    0,0,40  ; dH=+0 dL=+0 tile=40
        dc.b    255,0,26  ; dH=-1 dL=+0 tile=26
        dc.b    255,255,184  ; dH=-1 dL=-1 tile=184
        dc.b    254,0,185  ; dH=-2 dL=+0 tile=185
        dc.b    254,255,187  ; dH=-2 dL=-1 tile=187
; type $5A (5 sub-tiles)
        dc.b    5
        dc.b    0,0,43  ; dH=+0 dL=+0 tile=43
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,1,108  ; dH=-1 dL=+1 tile=108
        dc.b    254,0,172  ; dH=-2 dL=+0 tile=172
        dc.b    254,1,174  ; dH=-2 dL=+1 tile=174
; type $5C (9 sub-tiles)
        dc.b    9
        dc.b    255,0,43  ; dH=-1 dL=+0 tile=43
        dc.b    255,1,86  ; dH=-1 dL=+1 tile=86
        dc.b    254,1,80  ; dH=-2 dL=+1 tile=80
        dc.b    253,1,81  ; dH=-3 dL=+1 tile=81
        dc.b    252,1,82  ; dH=-4 dL=+1 tile=82
        dc.b    0,0,86  ; dH=+0 dL=+0 tile=86
        dc.b    255,0,87  ; dH=-1 dL=+0 tile=87
        dc.b    254,0,85  ; dH=-2 dL=+0 tile=85
        dc.b    253,0,84  ; dH=-3 dL=+0 tile=84
; type $5E (9 sub-tiles)
        dc.b    9
        dc.b    255,0,40  ; dH=-1 dL=+0 tile=40
        dc.b    255,255,0  ; dH=-1 dL=-1 tile=0
        dc.b    254,255,119  ; dH=-2 dL=-1 tile=119
        dc.b    253,255,120  ; dH=-3 dL=-1 tile=120
        dc.b    252,255,121  ; dH=-4 dL=-1 tile=121
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,126  ; dH=-1 dL=+0 tile=126
        dc.b    254,0,124  ; dH=-2 dL=+0 tile=124
        dc.b    253,0,123  ; dH=-3 dL=+0 tile=123
; type $60 (4 sub-tiles)
        dc.b    4
        dc.b    0,1,42  ; dH=+0 dL=+1 tile=42
        dc.b    255,1,45  ; dH=-1 dL=+1 tile=45
        dc.b    255,2,40  ; dH=-1 dL=+2 tile=40
        dc.b    254,2,41  ; dH=-2 dL=+2 tile=41
; type $62 (4 sub-tiles)
        dc.b    4
        dc.b    0,1,0  ; dH=+0 dL=+1 tile=0
        dc.b    255,1,116  ; dH=-1 dL=+1 tile=116
        dc.b    255,2,98  ; dH=-1 dL=+2 tile=98
        dc.b    254,2,99  ; dH=-2 dL=+2 tile=99
; type $64 (15 sub-tiles)
        dc.b    15
        dc.b    253,0,42  ; dH=-3 dL=+0 tile=42
        dc.b    252,0,10  ; dH=-4 dL=+0 tile=10
        dc.b    251,0,10  ; dH=-5 dL=+0 tile=10
        dc.b    250,0,10  ; dH=-6 dL=+0 tile=10
        dc.b    249,0,10  ; dH=-7 dL=+0 tile=10
        dc.b    248,0,90  ; dH=-8 dL=+0 tile=90
        dc.b    0,0,94  ; dH=+0 dL=+0 tile=94
        dc.b    255,0,93  ; dH=-1 dL=+0 tile=93
        dc.b    254,0,93  ; dH=-2 dL=+0 tile=93
        dc.b    253,0,93  ; dH=-3 dL=+0 tile=93
        dc.b    252,0,93  ; dH=-4 dL=+0 tile=93
        dc.b    251,0,92  ; dH=-5 dL=+0 tile=92
        dc.b    250,0,91  ; dH=-6 dL=+0 tile=91
        dc.b    250,1,90  ; dH=-6 dL=+1 tile=90
        dc.b    249,1,9  ; dH=-7 dL=+1 tile=9
; type $66 (6 sub-tiles)
        dc.b    6
        dc.b    255,2,214  ; dH=-1 dL=+2 tile=214
        dc.b    254,2,0  ; dH=-2 dL=+2 tile=0
        dc.b    253,2,171  ; dH=-3 dL=+2 tile=171
        dc.b    1,0,0  ; dH=+1 dL=+0 tile=0
        dc.b    0,0,209  ; dH=+0 dL=+0 tile=209
        dc.b    255,0,168  ; dH=-1 dL=+0 tile=168
; type $68 (4 sub-tiles)
        dc.b    4
        dc.b    255,2,170  ; dH=-1 dL=+2 tile=170
        dc.b    254,2,171  ; dH=-2 dL=+2 tile=171
        dc.b    1,0,0  ; dH=+1 dL=+0 tile=0
        dc.b    0,0,168  ; dH=+0 dL=+0 tile=168
; type $6A (unused)
        dc.b    0
; type $6C (6 sub-tiles)
        dc.b    6
        dc.b    0,1,55  ; dH=+0 dL=+1 tile=55
        dc.b    255,1,53  ; dH=-1 dL=+1 tile=53
        dc.b    254,1,53  ; dH=-2 dL=+1 tile=53
        dc.b    1,2,51  ; dH=+1 dL=+2 tile=51
        dc.b    0,2,51  ; dH=+0 dL=+2 tile=51
        dc.b    255,2,50  ; dH=-1 dL=+2 tile=50
; type $6E (6 sub-tiles)
        dc.b    6
        dc.b    0,1,38  ; dH=+0 dL=+1 tile=38
        dc.b    255,1,76  ; dH=-1 dL=+1 tile=76
        dc.b    254,1,75  ; dH=-2 dL=+1 tile=75
        dc.b    1,0,42  ; dH=+1 dL=+0 tile=42
        dc.b    0,0,73  ; dH=+0 dL=+0 tile=73
        dc.b    255,0,74  ; dH=-1 dL=+0 tile=74
; type $70 (8 sub-tiles)
        dc.b    8
        dc.b    0,0,43  ; dH=+0 dL=+0 tile=43
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,0,45  ; dH=-1 dL=+0 tile=45
        dc.b    254,0,0  ; dH=-2 dL=+0 tile=0
        dc.b    0,1,40  ; dH=+0 dL=+1 tile=40
        dc.b    255,1,0  ; dH=-1 dL=+1 tile=0
        dc.b    255,1,41  ; dH=-1 dL=+1 tile=41
        dc.b    254,1,136  ; dH=-2 dL=+1 tile=136
; type $72 (8 sub-tiles)
        dc.b    8
        dc.b    0,0,40  ; dH=+0 dL=+0 tile=40
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,0,41  ; dH=-1 dL=+0 tile=41
        dc.b    254,0,0  ; dH=-2 dL=+0 tile=0
        dc.b    0,255,43  ; dH=+0 dL=-1 tile=43
        dc.b    255,255,0  ; dH=-1 dL=-1 tile=0
        dc.b    255,255,45  ; dH=-1 dL=-1 tile=45
        dc.b    254,255,207  ; dH=-2 dL=-1 tile=207
; type $74 (8 sub-tiles)
        dc.b    8
        dc.b    0,1,43  ; dH=+0 dL=+1 tile=43
        dc.b    255,1,0  ; dH=-1 dL=+1 tile=0
        dc.b    255,1,45  ; dH=-1 dL=+1 tile=45
        dc.b    254,1,0  ; dH=-2 dL=+1 tile=0
        dc.b    0,2,40  ; dH=+0 dL=+2 tile=40
        dc.b    255,2,0  ; dH=-1 dL=+2 tile=0
        dc.b    255,2,41  ; dH=-1 dL=+2 tile=41
        dc.b    254,2,136  ; dH=-2 dL=+2 tile=136
; type $76 (5 sub-tiles)
        dc.b    5
        dc.b    0,0,94  ; dH=+0 dL=+0 tile=94
        dc.b    255,0,203  ; dH=-1 dL=+0 tile=203
        dc.b    254,0,205  ; dH=-2 dL=+0 tile=205
        dc.b    253,0,202  ; dH=-3 dL=+0 tile=202
        dc.b    252,0,70  ; dH=-4 dL=+0 tile=70
; type $78 (5 sub-tiles)
        dc.b    5
        dc.b    0,0,95  ; dH=+0 dL=+0 tile=95
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    254,0,205  ; dH=-2 dL=+0 tile=205
        dc.b    253,0,204  ; dH=-3 dL=+0 tile=204
        dc.b    252,0,96  ; dH=-4 dL=+0 tile=96
; type $7A (5 sub-tiles)
        dc.b    5
        dc.b    0,0,109  ; dH=+0 dL=+0 tile=109
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    254,0,205  ; dH=-2 dL=+0 tile=205
        dc.b    253,0,204  ; dH=-3 dL=+0 tile=204
        dc.b    252,0,96  ; dH=-4 dL=+0 tile=96
; type $7C (2 sub-tiles)
        dc.b    2
        dc.b    0,0,88  ; dH=+0 dL=+0 tile=88
        dc.b    255,0,86  ; dH=-1 dL=+0 tile=86
; type $7E (4 sub-tiles)
        dc.b    4
        dc.b    255,2,40  ; dH=-1 dL=+2 tile=40
        dc.b    254,2,41  ; dH=-2 dL=+2 tile=41
        dc.b    0,1,42  ; dH=+0 dL=+1 tile=42
        dc.b    255,1,45  ; dH=-1 dL=+1 tile=45
; type $80 (4 sub-tiles)
        dc.b    4
        dc.b    1,0,42  ; dH=+1 dL=+0 tile=42
        dc.b    0,0,45  ; dH=+0 dL=+0 tile=45
        dc.b    0,1,40  ; dH=+0 dL=+1 tile=40
        dc.b    255,1,41  ; dH=-1 dL=+1 tile=41
; type $82 (3 sub-tiles)
        dc.b    3
        dc.b    0,0,42  ; dH=+0 dL=+0 tile=42
        dc.b    255,0,73  ; dH=-1 dL=+0 tile=73
        dc.b    254,0,74  ; dH=-2 dL=+0 tile=74
; type $84 (3 sub-tiles)
        dc.b    3
        dc.b    0,0,38  ; dH=+0 dL=+0 tile=38
        dc.b    255,0,76  ; dH=-1 dL=+0 tile=76
        dc.b    254,0,75  ; dH=-2 dL=+0 tile=75
; type $86 (21 sub-tiles)
        dc.b    21
        dc.b    252,1,42  ; dH=-4 dL=+1 tile=42
        dc.b    251,1,10  ; dH=-5 dL=+1 tile=10
        dc.b    250,1,10  ; dH=-6 dL=+1 tile=10
        dc.b    249,1,10  ; dH=-7 dL=+1 tile=10
        dc.b    248,1,10  ; dH=-8 dL=+1 tile=10
        dc.b    0,1,94  ; dH=+0 dL=+1 tile=94
        dc.b    255,1,93  ; dH=-1 dL=+1 tile=93
        dc.b    254,1,93  ; dH=-2 dL=+1 tile=93
        dc.b    253,1,93  ; dH=-3 dL=+1 tile=93
        dc.b    252,1,93  ; dH=-4 dL=+1 tile=93
        dc.b    251,1,92  ; dH=-5 dL=+1 tile=92
        dc.b    250,1,91  ; dH=-6 dL=+1 tile=91
        dc.b    250,2,90  ; dH=-6 dL=+2 tile=90
        dc.b    249,2,9  ; dH=-7 dL=+2 tile=9
        dc.b    254,2,40  ; dH=-2 dL=+2 tile=40
        dc.b    253,2,9  ; dH=-3 dL=+2 tile=9
        dc.b    252,2,9  ; dH=-4 dL=+2 tile=9
        dc.b    251,2,9  ; dH=-5 dL=+2 tile=9
        dc.b    250,2,9  ; dH=-6 dL=+2 tile=9
        dc.b    249,2,9  ; dH=-7 dL=+2 tile=9
        dc.b    248,2,9  ; dH=-8 dL=+2 tile=9
; type $88 (22 sub-tiles)
        dc.b    22
        dc.b    254,255,42  ; dH=-2 dL=-1 tile=42
        dc.b    253,255,10  ; dH=-3 dL=-1 tile=10
        dc.b    252,255,10  ; dH=-4 dL=-1 tile=10
        dc.b    251,255,10  ; dH=-5 dL=-1 tile=10
        dc.b    250,255,10  ; dH=-6 dL=-1 tile=10
        dc.b    249,255,90  ; dH=-7 dL=-1 tile=90
        dc.b    0,1,94  ; dH=+0 dL=+1 tile=94
        dc.b    255,1,93  ; dH=-1 dL=+1 tile=93
        dc.b    254,1,93  ; dH=-2 dL=+1 tile=93
        dc.b    253,1,93  ; dH=-3 dL=+1 tile=93
        dc.b    252,1,93  ; dH=-4 dL=+1 tile=93
        dc.b    251,1,92  ; dH=-5 dL=+1 tile=92
        dc.b    250,1,91  ; dH=-6 dL=+1 tile=91
        dc.b    250,0,90  ; dH=-6 dL=+0 tile=90
        dc.b    249,0,9  ; dH=-7 dL=+0 tile=9
        dc.b    254,254,43  ; dH=-2 dL=-2 tile=43
        dc.b    253,254,10  ; dH=-3 dL=-2 tile=10
        dc.b    252,254,10  ; dH=-4 dL=-2 tile=10
        dc.b    251,254,10  ; dH=-5 dL=-2 tile=10
        dc.b    250,254,10  ; dH=-6 dL=-2 tile=10
        dc.b    249,254,10  ; dH=-7 dL=-2 tile=10
        dc.b    248,254,10  ; dH=-8 dL=-2 tile=10
; type $8A (10 sub-tiles)
        dc.b    10
        dc.b    1,255,65  ; dH=+1 dL=-1 tile=65
        dc.b    0,255,71  ; dH=+0 dL=-1 tile=71
        dc.b    255,255,117  ; dH=-1 dL=-1 tile=117
        dc.b    2,0,64  ; dH=+2 dL=+0 tile=64
        dc.b    1,0,56  ; dH=+1 dL=+0 tile=56
        dc.b    0,0,8  ; dH=+0 dL=+0 tile=8
        dc.b    255,0,118  ; dH=-1 dL=+0 tile=118
        dc.b    2,1,31  ; dH=+2 dL=+1 tile=31
        dc.b    1,1,32  ; dH=+1 dL=+1 tile=32
        dc.b    0,1,66  ; dH=+0 dL=+1 tile=66
; type $8C (10 sub-tiles)
        dc.b    10
        dc.b    1,1,103  ; dH=+1 dL=+1 tile=103
        dc.b    0,1,72  ; dH=+0 dL=+1 tile=72
        dc.b    255,1,118  ; dH=-1 dL=+1 tile=118
        dc.b    2,0,102  ; dH=+2 dL=+0 tile=102
        dc.b    1,0,104  ; dH=+1 dL=+0 tile=104
        dc.b    0,0,8  ; dH=+0 dL=+0 tile=8
        dc.b    255,0,117  ; dH=-1 dL=+0 tile=117
        dc.b    2,255,100  ; dH=+2 dL=-1 tile=100
        dc.b    1,255,101  ; dH=+1 dL=-1 tile=101
        dc.b    0,255,59  ; dH=+0 dL=-1 tile=59
; type $8E (4 sub-tiles)
        dc.b    4
        dc.b    0,1,40  ; dH=+0 dL=+1 tile=40
        dc.b    255,1,41  ; dH=-1 dL=+1 tile=41
        dc.b    255,2,42  ; dH=-1 dL=+2 tile=42
        dc.b    254,2,45  ; dH=-2 dL=+2 tile=45
; type $90 (4 sub-tiles)
        dc.b    4
        dc.b    0,1,98  ; dH=+0 dL=+1 tile=98
        dc.b    255,1,99  ; dH=-1 dL=+1 tile=99
        dc.b    255,2,0  ; dH=-1 dL=+2 tile=0
        dc.b    254,2,116  ; dH=-2 dL=+2 tile=116
; type $92 (5 sub-tiles)
        dc.b    5
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,1,0  ; dH=-1 dL=+1 tile=0
        dc.b    254,1,66  ; dH=-2 dL=+1 tile=66
        dc.b    254,0,68  ; dH=-2 dL=+0 tile=68
; type $94 (13 sub-tiles)
        dc.b    13
        dc.b    1,255,65  ; dH=+1 dL=-1 tile=65
        dc.b    0,255,23  ; dH=+0 dL=-1 tile=23
        dc.b    255,255,22  ; dH=-1 dL=-1 tile=22
        dc.b    254,255,26  ; dH=-2 dL=-1 tile=26
        dc.b    2,0,64  ; dH=+2 dL=+0 tile=64
        dc.b    1,0,21  ; dH=+1 dL=+0 tile=21
        dc.b    0,0,24  ; dH=+0 dL=+0 tile=24
        dc.b    255,0,29  ; dH=-1 dL=+0 tile=29
        dc.b    254,0,30  ; dH=-2 dL=+0 tile=30
        dc.b    2,1,31  ; dH=+2 dL=+1 tile=31
        dc.b    1,1,32  ; dH=+1 dL=+1 tile=32
        dc.b    0,1,25  ; dH=+0 dL=+1 tile=25
        dc.b    255,1,20  ; dH=-1 dL=+1 tile=20
; type $96 (1 sub-tiles)
        dc.b    1
        dc.b    0,1,227  ; dH=+0 dL=+1 tile=227
; type $98 (2 sub-tiles)
        dc.b    2
        dc.b    0,0,49  ; dH=+0 dL=+0 tile=49
        dc.b    255,0,14  ; dH=-1 dL=+0 tile=14
; type $9A (3 sub-tiles)
        dc.b    3
        dc.b    0,0,13  ; dH=+0 dL=+0 tile=13
        dc.b    255,0,12  ; dH=-1 dL=+0 tile=12
        dc.b    254,0,11  ; dH=-2 dL=+0 tile=11
; type $9C (5 sub-tiles)
        dc.b    5
        dc.b    0,0,0  ; dH=+0 dL=+0 tile=0
        dc.b    255,0,0  ; dH=-1 dL=+0 tile=0
        dc.b    255,1,0  ; dH=-1 dL=+1 tile=0
        dc.b    254,1,0  ; dH=-2 dL=+1 tile=0
        dc.b    254,0,218  ; dH=-2 dL=+0 tile=218
; type $9E (8 sub-tiles)
        dc.b    8
        dc.b    0,0,40  ; dH=+0 dL=+0 tile=40
        dc.b    255,0,3  ; dH=-1 dL=+0 tile=3
        dc.b    255,0,41  ; dH=-1 dL=+0 tile=41
        dc.b    254,0,78  ; dH=-2 dL=+0 tile=78
        dc.b    0,255,43  ; dH=+0 dL=-1 tile=43
        dc.b    255,255,3  ; dH=-1 dL=-1 tile=3
        dc.b    255,255,45  ; dH=-1 dL=-1 tile=45
        dc.b    254,255,89  ; dH=-2 dL=-1 tile=89

        even
