; ============================================================
; palette_data.s - GENERATED by tools/mkpalette.py from data/colour_mapping.json
; (edit the mapping with tools/colour_mapper.html, not this file)
; CPC palettes 0 black, 1 parchment, 2 day, 3 night -> QL Mode 8 colour words, pens 0-3.
; pal_table, 64 bytes a palette: terrain even/odd lines, characters even/odd,
; panel even/odd (4 words each), flags word (bit 0: characters differ), padding.
; ============================================================
        cnop    0,2
pal_table:
        ; 0 black
        dc.w    $0000,$0000,$0000,$0000   ; terrain even lines
        dc.w    $0000,$0000,$0000,$0000   ; terrain odd lines
        dc.w    $0000,$0000,$0000,$0000   ; characters even lines
        dc.w    $0000,$0000,$0000,$0000   ; characters odd lines
        dc.w    $0000,$0000,$0000,$0000   ; panel even lines
        dc.w    $0000,$0000,$0000,$0000   ; panel odd lines
        dc.w    0   ; flags
        ds.w    7
        ; 1 parchment
        dc.w    $AABB,$AA55,$0000,$00AA   ; terrain even lines
        dc.w    $AAEE,$AA55,$0000,$00AA   ; terrain odd lines
        dc.w    $AABB,$AA55,$0000,$00AA   ; characters even lines
        dc.w    $AAEE,$AA55,$0000,$00AA   ; characters odd lines
        dc.w    $AABB,$AA55,$0000,$00AA   ; panel even lines
        dc.w    $AAEE,$AA55,$0000,$00AA   ; panel odd lines
        dc.w    0   ; flags
        ds.w    7
        ; 2 day (separate character colours)
        dc.w    $AA55,$AAAA,$AAFF,$0000   ; terrain even lines
        dc.w    $AA55,$AAAA,$AAFF,$0000   ; terrain odd lines
        dc.w    $AAFF,$00AA,$AAAA,$0000   ; characters even lines
        dc.w    $AAFF,$00AA,$AAAA,$0000   ; characters odd lines
        dc.w    $AAFF,$AAAA,$00AA,$0000   ; panel even lines
        dc.w    $AAFF,$AAAA,$00AA,$0000   ; panel odd lines
        dc.w    1   ; flags
        ds.w    7
        ; 3 night (separate character colours)
        dc.w    $0055,$00FF,$AAFF,$0000   ; terrain even lines
        dc.w    $0055,$00FF,$AAFF,$0000   ; terrain odd lines
        dc.w    $0055,$AA55,$AAFF,$0000   ; characters even lines
        dc.w    $0055,$AA55,$AAFF,$0000   ; characters odd lines
        dc.w    $0055,$00FF,$AAFF,$0000   ; panel even lines
        dc.w    $0055,$00FF,$AAFF,$0000   ; panel odd lines
        dc.w    1   ; flags
        ds.w    7

; the pre-CHARCOL table (terrain even-line words), for the code kept assembled out
palettes:
        dc.w    $0000,$0000,$0000,$0000   ; 0 black
        dc.w    $AABB,$AA55,$0000,$00AA   ; 1 parchment
        dc.w    $AA55,$AAAA,$AAFF,$0000   ; 2 day
        dc.w    $0055,$00FF,$AAFF,$0000   ; 3 night
