; ============================================================
; room_ptrs.s - Room pointer table and palette
; Generated by convert_rooms.py - DO NOT EDIT
; Included near rooms.s for PC-relative addressing.
; Actual room data is in room_data.s (at end of binary).
; ============================================================

ROOM_COUNT equ 59

; Room pointer table (word offsets from room_data_base)
; Offset $FFFF = invalid room
room_ptr_table:
        dc.w    room_0-room_data_base  ; Room 0
        dc.w    $FFFF  ; Room 1 (invalid)
        dc.w    room_2-room_data_base  ; Room 2
        dc.w    room_3-room_data_base  ; Room 3
        dc.w    room_4-room_data_base  ; Room 4
        dc.w    room_5-room_data_base  ; Room 5
        dc.w    room_6-room_data_base  ; Room 6
        dc.w    room_7-room_data_base  ; Room 7
        dc.w    room_8-room_data_base  ; Room 8
        dc.w    room_9-room_data_base  ; Room 9
        dc.w    room_10-room_data_base  ; Room 10
        dc.w    room_11-room_data_base  ; Room 11
        dc.w    room_12-room_data_base  ; Room 12
        dc.w    $FFFF  ; Room 13 (invalid)
        dc.w    room_14-room_data_base  ; Room 14
        dc.w    room_15-room_data_base  ; Room 15
        dc.w    room_16-room_data_base  ; Room 16
        dc.w    room_17-room_data_base  ; Room 17
        dc.w    room_18-room_data_base  ; Room 18
        dc.w    room_19-room_data_base  ; Room 19
        dc.w    room_20-room_data_base  ; Room 20
        dc.w    room_21-room_data_base  ; Room 21
        dc.w    room_22-room_data_base  ; Room 22
        dc.w    room_23-room_data_base  ; Room 23
        dc.w    room_24-room_data_base  ; Room 24
        dc.w    room_25-room_data_base  ; Room 25
        dc.w    room_26-room_data_base  ; Room 26
        dc.w    room_27-room_data_base  ; Room 27
        dc.w    room_28-room_data_base  ; Room 28
        dc.w    room_29-room_data_base  ; Room 29
        dc.w    room_30-room_data_base  ; Room 30
        dc.w    room_31-room_data_base  ; Room 31
        dc.w    room_32-room_data_base  ; Room 32
        dc.w    room_33-room_data_base  ; Room 33
        dc.w    room_34-room_data_base  ; Room 34
        dc.w    room_35-room_data_base  ; Room 35
        dc.w    room_36-room_data_base  ; Room 36
        dc.w    room_37-room_data_base  ; Room 37
        dc.w    room_38-room_data_base  ; Room 38
        dc.w    room_39-room_data_base  ; Room 39
        dc.w    room_40-room_data_base  ; Room 40
        dc.w    room_41-room_data_base  ; Room 41
        dc.w    room_42-room_data_base  ; Room 42
        dc.w    room_43-room_data_base  ; Room 43
        dc.w    room_44-room_data_base  ; Room 44
        dc.w    room_45-room_data_base  ; Room 45
        dc.w    room_46-room_data_base  ; Room 46
        dc.w    room_47-room_data_base  ; Room 47
        dc.w    room_48-room_data_base  ; Room 48
        dc.w    room_49-room_data_base  ; Room 49
        dc.w    room_50-room_data_base  ; Room 50
        dc.w    room_51-room_data_base  ; Room 51
        dc.w    room_52-room_data_base  ; Room 52
        dc.w    room_53-room_data_base  ; Room 53
        dc.w    $FFFF  ; Room 54 (invalid)
        dc.w    room_55-room_data_base  ; Room 55
        dc.w    room_56-room_data_base  ; Room 56
        dc.w    room_57-room_data_base  ; Room 57
        dc.w    room_58-room_data_base  ; Room 58

; Room palette bytes (from ABADIA6.BIN)
room_palette:
        dc.b    $BF  ; Room 0
        dc.b    $00  ; Room 1
        dc.b    $CF  ; Room 2
        dc.b    $DF  ; Room 3
        dc.b    $DB  ; Room 4
        dc.b    $DF  ; Room 5
        dc.b    $CF  ; Room 6
        dc.b    $DF  ; Room 7
        dc.b    $DB  ; Room 8
        dc.b    $DF  ; Room 9
        dc.b    $FF  ; Room 10
        dc.b    $FE  ; Room 11
        dc.b    $BE  ; Room 12
        dc.b    $00  ; Room 13
        dc.b    $CF  ; Room 14
        dc.b    $DF  ; Room 15
        dc.b    $DB  ; Room 16
        dc.b    $DF  ; Room 17
        dc.b    $CF  ; Room 18
        dc.b    $DF  ; Room 19
        dc.b    $DB  ; Room 20
        dc.b    $DF  ; Room 21
        dc.b    $DB  ; Room 22
        dc.b    $DF  ; Room 23
        dc.b    $CF  ; Room 24
        dc.b    $DF  ; Room 25
        dc.b    $DB  ; Room 26
        dc.b    $DF  ; Room 27
        dc.b    $CF  ; Room 28
        dc.b    $DF  ; Room 29
        dc.b    $DB  ; Room 30
        dc.b    $DF  ; Room 31
        dc.b    $CF  ; Room 32
        dc.b    $DF  ; Room 33
        dc.b    $DB  ; Room 34
        dc.b    $DF  ; Room 35
        dc.b    $DB  ; Room 36
        dc.b    $DF  ; Room 37
        dc.b    $CF  ; Room 38
        dc.b    $FF  ; Room 39
        dc.b    $FD  ; Room 40
        dc.b    $FF  ; Room 41
        dc.b    $EF  ; Room 42
        dc.b    $FF  ; Room 43
        dc.b    $DF  ; Room 44
        dc.b    $DB  ; Room 45
        dc.b    $DF  ; Room 46
        dc.b    $DB  ; Room 47
        dc.b    $DF  ; Room 48
        dc.b    $FF  ; Room 49
        dc.b    $FB  ; Room 50
        dc.b    $FF  ; Room 51
        dc.b    $FE  ; Room 52
        dc.b    $BE  ; Room 53
        dc.b    $00  ; Room 54
        dc.b    $FE  ; Room 55
        dc.b    $FE  ; Room 56
        dc.b    $FF  ; Room 57
        dc.b    $BF  ; Room 58
        even
